### ISSUE TITLE
Can't parse old replay files from early days of LotV - Invalid replay file.

### ISSUE THREAD

**Issue by Xeizzen** [icza/s2prot#4]
Example of such a replay: https://drop.sc/replay/6694231

But as I can see drop.sc is also has a hard time dealing with the replay for some reason.
But original s2protocol module for python can parse it without problems.

**Update:**
Additional replays just in case: https://www.dropbox.com/s/l7vaotpgkh8wraw/old_replays.zip?dl=1
And I can tell that the names of the replays were changed by the python script, hence some time in the past they've been successfully parsed by original s2protocol.

**Comment by Xeizzen** [comment]
False alarm.

**Comment by icza** [comment]
Does this mean s2prot was able to parse these replays?

**Comment by Xeizzen** [comment]
I still figuring out the problem but it seems like at least header is able to be processed.

**Comment by amartin916** [comment]
On drop.sc/sc2replaystats the problem was caused by me checking a section that was not added in that replay version (3.2.1.41973) Icza the section I was checking was replay.gamemetadata.json which was not added until recently. 

`contents = archive.read_file('replay.gamemetadata.json')`

Also I fixed the drop.sc replay so its loads correctly now :)

**Comment by icza** [comment]
Good, @amartin916, thanks for the feedback. So can this be closed?
