### ISSUE TITLE
Unable to identify the unranked league?

### ISSUE THREAD

**Issue by ghost** [icza/s2prot#8]
Looks like the library sometimes can't identify the unranked league.
While it could identify it in earlier builds of the game.

https://www.dropbox.com/s/dzqulrhf4io1bce/unranked_league.zip?dl=1

But ofc. there could be a possibility of it be the problem on my side.
The code:
```
leagues := string(primary_player.PlayerInitData.HighestLeague().Letter) + "v" +
	string(secondary_player.PlayerInitData.HighestLeague().Letter)
```

**Comment by icza** [comment]
I don't see any problems with league parsing. Note that not all (or even none) of the players may have a league recorded in replays, this is especially true after the start of a new season. If a player has unknown league, that may very well mean the user is playing his / her placement matches, or simply he /  she is playing unranked game (and not ranked).

I took the first replay from the pack you sent: `PvP Dv- 0 v 3105 WIN - Catalyst LE (2018y-02m-19d_16h-46m-58s).SC2Replay`.

And using the latest code from the master branch, I ran the following small app on it:

	r, err := rep.NewFromFile("unranked_league/PvP Dv- 0 v 3105 WIN - Catalyst LE (2018y-02m-19d_16h-46m-58s).SC2Replay")
	if err != nil {
		fmt.Printf("%v\n", err)
		return
	}
	defer r.Close()

	for _, u := range r.InitData.UserInitDatas {
		fmt.Println(u.Name(), u.HighestLeague(), string(u.HighestLeague().Letter))
	}

The output is:

```
Pepsi Unknown -
Xeizzen Diamond D
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
 Unknown -
```

As you can see, league of `Xeizzen` was detected: `Diamond`.

**Comment by Xeizzen** [comment]
League of Xeizzen was detected, yes, but I don't point at Xeizzen's league. I point at opponent's.
We should use the unranked league instead of unknown because there can't be an "unknown" league, only unranked one.

And ofc. I know how the ladder of sc2 is working so you can skip telling me that.

**Comment by Xeizzen** [comment]
Also looks like we can determine the unranked league from the replays of an earlier version of the game.
If, ofc. "u" stands for "unranked".

https://www.dropbox.com/s/w164bocu9havmjc/New%20folder.7z?dl=1

**Comment by icza** [comment]
This is how replays are saved. When s2prot reports "Unknown", the `highestLeague` field in the replay is `0`. When s2prot reports "Unranked", the `highestLeague` field in the replay is `8`.

The replays you sent me have `highestLeague=0`.

**Comment by Xeizzen** [comment]
I think you should change it to "unranked" league. It is just doesn't feel right.
Besides, I believe original s2protocol python library had the definition for the unranked league as 0. Not quite sure about this, because I used this python module long ago, and can forget the details.
Don't know how else to convince you.

**Comment by icza** [comment]
If you can show me some credible sources that the `0` value stands for unranked now, I'll change it. The value `8` was reserved for unranked in the past, and the `0` was not identical to unranked.

**Comment by Xeizzen** [comment]
I see that this issue still marked as opened.
Well, I can't answer to your request, because all reliable source have only abstract representation of the data that is topic of our discussions, so it is up for a player/designer/programmer to decide what this data should mean/represent.
But I can repeat that in the game itself there is no such league as "unknown", so... I guess we should rename it to "unranked"? Which in turn will put us in the situation that we have two "unranked" leagues.
But we can went to other direction: mark it too as a letter "U" in the short version? So both "unknown" and "unranked" leagues will be represented the same in short version, but differently in long version.

**Comment by icza** [comment]
Without testing, I'd say if you play offline, the league will be `Unknown`. So I wouldn't shut it out so fast...

**Comment by Xeizzen** [comment]
Well, whatever you chose to code. This is your project.
But I will appreciate and would like to see the short version of the league also be present not just as "-", but as "u", no matter what the long name is.

**Comment by icza** [comment]
Please note that the `League`  enum values are variables. This means you can change their properties to your liking in your application. For example if you want the `Unknown` league to have a short representation (letter) to be `'U'`, this is all it takes:

    rep.LeagueUnknown.Letter = 'U'

Does this satisfies you?

**Comment by Xeizzen** [comment]
Fair enough, thanks for the suggestion :+1:

**Comment by icza** [comment]
Closing the issue now.
